Hotfix/employee feedback#256
ISPP-GRUPO-8/BANQUETBUDDY pull request #263
Opened 2024-05-01 11:23 UTC by marrocrod

## Título #NÚMERO_DE_ISSUE

### Descripción

Implementadas las siguientes recomendaciones del feedback recibido:

- Añadir campos de experience y profession y en el perfil del usuario
- Editar campos de experience y profession
- Validaciones sobre nombre y apellidos con espacios, mínima longitud añadida y no se admiten caracteres que no sean letras
- Añadir buscador en ofertas y modificar el tag del buscador
- Mostrar que no hay ofertas con un parámetro pasado cuando se buscan
- Mostrar que no hay ofertas disponibles cuando se buscan
- Añadida página de feedback sobre un error_report enviado

### Contexto Adicional

Probado con la rama develop del 26/04 . En settings.py se ha cambiado la contraseña a "issp", se debería dejar como DB_PASSWORD.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [x] Se ha probado que la aplicación se levanta en local.
- [ ] Se ha probado que los cambios se integran bien en la aplicación.
- [ ] Se ha probado que los cambios corresponden con los solicitados en la tarea.

2024-05-05 00:25 UTC, marrocrod commented
Arreglado.

2024-05-05 17:29 UTC, Pablomv8 requested changes
Al editar el perfil no funciona correctamente lo siguiente:
- Al poner nombre y apellidos devuelve que no pueden superar los 150 caracteres como se ve en la imagen
- No reconoce las tildes y devuelve que solo se pueden usar letras y espacios, adjunto imagen también

![Captura de pantalla (116)](https://github.com/ISPP-GRUPO-8/BANQUETBUDDY/assets/81299802/7a2dac2a-dfe1-4176-b250-f59f486284bb)
![Captura de pantalla (117)](https://github.com/ISPP-GRUPO-8/BANQUETBUDDY/assets/81299802/23e6f2f1-395d-4d15-bc71-77f3f1db8f18)

2024-05-05 17:34 UTC, marsannar2 requested changes
He comprobado que funciona el buscador de ofertas y que el mensaje de reporte enviado aparece. Sin embargo, he tenido los mismos problemas de registro que Pablo, es decir, al ingresar mi nombre y apellido, me aparece el siguiente mensaje:
"First name and last name must have less than 150 characters"

Tampoco me deja poner tildes,que supongo que el registro lo detectará como un carácter especial"

2024-05-06 11:31 UTC, marsannar2 requested changes
Cuando intento poner un nombre y apellido con más de 150 carácteres,no me salta el error 
"First name and last name must have less than 150 characters",pero al menos se limita el input a 150 palabras(porque obviamente al limitar el input a 150 palabras nunca va a saltar ese mensaje)
![image](https://github.com/ISPP-GRUPO-8/BANQUETBUDDY/assets/67070527/e70ffef6-be0b-489c-89b9-7664a2fdc49c)
![image](https://github.com/ISPP-GRUPO-8/BANQUETBUDDY/assets/67070527/f8f6c366-9aaf-4f6e-8026-4c365327be7f)

2024-05-06 17:02 UTC, marsannar2 approved these changes
He revisado que salta un mensaje de error al escribir mas de 150 carácteres en nombre y apellido

2024-05-06 17:37 UTC, Pablomv8 approved these changes
Ya funciona correctamente

2024-05-06 18:07 UTC, merged