Feature/hired catering
ISPP-GRUPO-8/BANQUETBUDDY pull request #72
Opened 2024-03-11 18:47 UTC by gonsanmar2

2024-03-15 12:26 UTC, Alvsanflo commented on banquetBuddy/catering_particular/urls.py
Fallo solucionado, a la espera de revisión y prueba del código

2024-03-15 12:36 UTC, javierrc8 requested changes

2024-03-15 12:36 UTC, javierrc8 commented on banquetBuddy/catering_particular/views.py
Da error en la línea 46 por un espacio antes del @login_required, además, el Event utilizado en la línea 50 debe ser importado del models de catering_owners.

2024-03-15 12:36 UTC, javierrc8 commented on banquetBuddy/catering_particular/views.py
Realizando estos cambios, todo funciona correctamente.

2024-03-18 17:05 UTC, Alvsanflo approved these changes

2024-03-25 10:49 UTC, javierrc8 approved these changes
Todo correcto.

2024-03-26 17:12 UTC, merged