Feature/particular book cancellation and modification
ISPP-GRUPO-8/BANQUETBUDDY pull request #85
Opened 2024-03-15 17:22 UTC by javierrc8

## R-053: Modificación y Cancelación de Reservas para Particulares #63

### Descripción

Se ha implementado y probado la funcionalidad que permite a los particulares editar y cancelar las reservas de caterings que han realizado.

### Contexto Adicional

La funcionalidad ha sido desarrollada para que solo los particulares puedan acceder a la pestaña. Esta pestaña se encuentra a la derecha en la barra de navegación. Por lo que para utilizarla se debe iniciar sesión con un particular.

## Lista de Verificación

- [x] Se ha probado que la aplicación se levanta en local.
- [x] Se ha probado que los cambios se integran bien en la aplicación.
- [x] Se ha probado que los cambios corresponden con los solicitados en la tarea.

2024-03-18 16:26 UTC, jaicabher1 requested changes
A la hora de editar un catering, al igual que se muestra el número de comensales y el día del evento para poder editarlos, debería salir el menú que estaba contratado.

2024-03-18 16:27 UTC, jaicabher1 commented
Lo demás todo perfecto.

2024-03-18 17:14 UTC, javierrc8 commented
Se ha realizado la petición, a la espera de la revisión. 👍🏽

2024-03-18 17:39 UTC, javierrc8 commented
Se han corregido algunos conflictos.

2024-03-18 23:15 UTC, jaicabher1 reviewed
Fallo corregido perfectamente, no veo ningún problema más. Resuelve el conflicto y podremos aceptar la pull.

2024-03-19 10:27 UTC, javierrc8 commented
Todo los conflictos y los cambios se han llevado a cabo, ante el paso del tiempo, mergeo la rama.

2024-03-19 10:27 UTC, merged