Feature/cancellation management catering
ISPP-GRUPO-8/BANQUETBUDDY pull request #90
Opened 2024-03-17 17:46 UTC by alvcarber1

## Título R-055: Modificación y Cancelación de Reservas para Empresas de Catering #64 

### Descripción

Se ha implementado y probado la funcionalidad que permite a los caterings editar y cancelar las reservas que los particulares hayan realizado.

### Contexto Adicional

La funcionalidad ha sido desarrollada para que solo los caterings puedan acceder a la pestaña. Esta pestaña se encuentra a la derecha en la barra de navegación. Por lo que para utilizarla se debe iniciar sesión con un catering.

## Lista de Verificación

Por favor, marca las casillas que correspondan:

- [ ] Se ha probado que la aplicación se levanta en local.
- [ ] Se ha probado que los cambios se integran bien en la aplicación.
- [ ] Se ha probado que los cambios corresponden con los solicitados en la tarea.

2024-03-18 10:23 UTC, jaicabher1 requested changes
Resuelve los conflictos, por favor

2024-03-18 11:14 UTC, alvcarber1 commented
Conflictos resueltos.

2024-03-18 23:11 UTC, jaicabher1 requested changes
Sigue habiendo conflictos.
![image](https://github.com/ISPP-GRUPO-8/BANQUETBUDDY/assets/73229534/a05085b6-6732-4a02-b8a8-527ea0f05652)

2024-03-19 10:27 UTC, alvcarber1 commented
Conflictos resueltos.

![137db41c-674c-42e3-89c6-09befc0e9a7b](https://github.com/ISPP-GRUPO-8/BANQUETBUDDY/assets/80391410/adefcfb9-cf2d-4c7f-995d-76997dd77e41)

2024-03-27 17:24 UTC, merged